version: '3'

services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: z_prefix_db
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data

  backend:
    build: ./backend/
    container_name: backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: docker
      DB_NAME: z_prefix_db
      DB_PORT: 5432
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend/
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend